// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMjDABXAdeyxg-Jt0FD4bvEs6NNwe0Cw',
    appId: '1:179325164971:web:78d81430024e7c28bd46ee',
    messagingSenderId: '179325164971',
    projectId: 'zesty-437',
    authDomain: 'zesty-437.firebaseapp.com',
    storageBucket: 'zesty-437.appspot.com',
    measurementId: 'G-HT2TEWC91H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCwawfPpWdSrktMrmigzfKeMqg_MkuVU',
    appId: '1:179325164971:android:470b2e6d65a90d27bd46ee',
    messagingSenderId: '179325164971',
    projectId: 'zesty-437',
    storageBucket: 'zesty-437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWJDcdnvqcRS6OoT2790wd8HPt_rou_g',
    appId: '1:179325164971:ios:34f154134362a7c4bd46ee',
    messagingSenderId: '179325164971',
    projectId: 'zesty-437',
    storageBucket: 'zesty-437.appspot.com',
    iosClientId: '179325164971-vm57ln9sqfk47p0tdcefnf8c628i94je.apps.googleusercontent.com',
    iosBundleId: 'cse437.cse437.zesty',
  );
}
