// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiCwawfPpWdSrktMrmigzfKeMqg_MkuVU',
    appId: '1:179325164971:android:470b2e6d65a90d27bd46ee',
    messagingSenderId: '179325164971',
    projectId: 'zesty-437',
    storageBucket: 'zesty-437.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbWJDcdnvqcRS6OoT2790wd8HPt_rou_g',
    appId: '1:179325164971:ios:18d749f63162022ebd46ee',
    messagingSenderId: '179325164971',
    projectId: 'zesty-437',
    storageBucket: 'zesty-437.appspot.com',
    androidClientId: '179325164971-1jrvhuf9vjn5jig53cu3s4i426jm99ip.apps.googleusercontent.com',
    iosClientId: '179325164971-ubic1i60ufcm12jnvt2pifk99ad5smfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
